HOST = "0.0.0.0"
PORT = 9000
TCP_SOCKET_BUFFER_SIZE = 500000
TCP_SOCKET_SERVER_LISTEN = 10
SOCK_TIMEOUT = 20

DEFAULT_VAL_DS = "val"
DEFAULT_MEASURE = "mean"
TRAIN_VAL_TEST_RATIO = [.8, .1, .1]
RECORD_RATE = 10
M_CONSTANT = 1
TEST_SCOPE = 'neighborhood'
INFERENCE_BATCH_SIZE = 512
